### PR TITLE
Add Averageable module

### PR DESCRIPTION
**Pull request by DougWelchons**
Hey, here is the Averageable module we worked on.

### CODE REVIEW

**Comment by brisag** [comment]
Love the implentation on the module!

**Comment by avjohnston** [comment]
Wish we could have had more time to implement this module, but looks great for what it is!

**Review by Diana20920 — APPROVED** [review]
Just an empty line comment from Hound on line 13, but otherwise, I am really glad that we got to implement a module 😎

**Comment by avjohnston** [comment]
Learn how to spell doug, A V E R A G E A B L E

**Comment by DougWelchons** [comment]
I don't what you're talking about Andrew!

**Pull request merged**
