### PR TITLE
Sales analyst refactors

### PR DESCRIPTION
**Pull request by brisag**
Sales analyst refactors! Take a look!

### CODE REVIEW

**Review by Diana20920 — APPROVED** [review]
Hound teaching me things! 
Looks great!!

**Comment by avjohnston** [comment]
Looks great Brisa, this is exactly what we talked about!

**Comment by brisag** [comment]
Thanks for all the positive feedback! Lets merge this thing!

**Review by DougWelchons — APPROVED** [review]
Looks good.

**Pull request merged**
